// Define the keyword and URL pairs
const keywordURLPairs = [
  ['iocl', 'https://iocl.com/'],
  ['bongaigaon refinery', 'https://iocl.com/bongaigaon-refinery'],
  ['guwahati refinery', 'https://iocl.com/pages/guwahati-refinery'],
  ['indian oil','https://iocl.com/about-indianoil'],
  ['indianoil','https://iocl.com/about-indianoil'],
  ['awards and recognitions','https://iocl.com/pages/AwardsandRecognitions'],
  ['logo','https://iocl.com/corporate-logo'],
  ['visions and values','https://iocl.com/our-vision-with-values'],
  ['leaders','https://iocl.com/pages/our-leadership'],
  ['leaderships','https://iocl.com/pages/our-leadership'],
  ['mascot','https://iocl.com/pages/brand-mascot'],
  ['business overview','https://iocl.com/pages/our-business-overview'],
  ['sitemap','https://iocl.com/pages/sitemap'],
  ['facebook', 'https://www.facebook.com/IndianOilCorpLimited'],
  ['twitter', 'https://www.twitter.com/indianOilcl'],
  ['youtube', 'https://www.youtube.com/channel/UC5ho18VZHwEFSahW0Q_o-6g/feed'],
  ['instagram','https://www.instagram.com/indianoilcorp'],
  ['insta','https://www.instagram.com/indianoilcorp'],
  ['linkedin','https://www.linkedin.com/company/indian-oil-corp-limited'],
  ['Rhino','https://iocl.com/pages/brand-mascot'],
  ['Single-horned rhino','https://iocl.com/pages/brand-mascot'],
  ['Single horned rhino','https://iocl.com/pages/brand-mascot'],
  ['One-horned rhino','https://iocl.com/pages/brand-mascot'],
  ['One horned rhino','https://iocl.com/pages/brand-mascot'],
  ['refining','https://iocl.com/pages/refining-overview'],
  ['refining overview','https://iocl.com/pages/refining-overview'],
  ['barauni refinery','https://iocl.com/barauni-refinery'],
  ['paradip refinery','https://iocl.com/paradip-refinery'],
  ['haldia refinery','https://iocl.com/haldia-refinery'],
  ['mathura refinery','https://iocl.com/mathura-refinery'],
  ['gujarat refinery','https://iocl.com/gujarat-refinery'],
  ['panipat refinery','https://iocl.com/pages/panipat-refinery'],
  ['digboi refinery','https://iocl.com/pages/digboi-refinery'],
  ['pipeline overview','https://iocl.com/Pages/pipelines-overview'],
  ['Pipeline Projects under Implementation','https://iocl.com/projects-under-implementation'],
  ['Crude Oil Pipelines','https://iocl.com/crude-oil-pipelines'],
  ['Petroleum Product Pipelines','https://iocl.com/petroleum-product-pipelines'],
  ['gas pipelines','https://iocl.com/gas-pipelines'],
  ['Pipeline Safety','https://iocl.com/pipeline-safety'],
  ['Crossing Permission Portal','https://crossing.indianoilpipelines.in/Crossing/Account/Login?returnUrl=%2FCrossing'],
  ['R&D Centre – Empowering the Innovation','https://iocl.com/pages/r-and-d-centre'],
  ['Research and development Centre – Empowering the Innovation','https://iocl.com/pages/r-and-d-centre'],
  ['R and D','https://iocl.com/pages/r-and-d-centre'],
  ['Marketing','https://iocl.com/marketing'],
  ['Petrochemicals', 'https://iocl.com/pages/Petrochemicals-Overview'],
  ['Natural Gas Overview', 'https://iocl.com/pages/natural-gas-overview'],
  ['Natural Gas Properties', 'https://iocl.com/natural-gas-properties'],
  ['Natural Gas Brochure', 'https://iocl.com/download/NaturalGas_Brochure.pdf'],
  ['City Gas Distribution(CGD)', 'https://iocl.com/pages/cgd'],
  ['cgd','https://iocl.com/pages/cgd'],
  ['Exploration and Production', 'https://iocl.com/pages/exploration-and-production'],
  ['e and p','https://iocl.com/pages/exploration-and-production'],
  ['Explosives', 'https://iocl.com/explosives'],
  ['Cryogenics', 'https://iocl.com/cryogenics'],
  ['Our Locations', 'https://iocl.com/our-locations'],
  ['Group companies Overview', 'https://iocl.com/pages/group-companies-overview'],
  ['company overview','https://iocl.com/pages/group-companies-overview'],
  ['Lanka IOC PLC', 'https://iocl.com/lanka-ioc-plc'],
  ['IndianOil Mauritius Ltd', 'https://iocl.com/indianoil-mauritius-ltd'],
  ['iml','https://iocl.com/indianoil-mauritius-ltd'],
  ['IOC Middle East FZE', 'https://iocl.com/ioc-middle-east-fze'],
  ['imef','https://iocl.com/ioc-middle-east-fze'],
  ['Chennai Petroleum Corporation Limited', 'https://iocl.com/chennai-petroleum-corporation-limited'],
  ['Glycols', 'https://iocl.com/glycols'],
  ['financial performance','https://iocl.com/pages/financial-performance-overview'],
  ['annual report','https://iocl.com/contents/AnnualReportenglish_2021-22/index.html'],
  ['annual report','https://iocl.com/contents/integrated-annual-report-2020-21/index.html'],
  ['podcast','https://iocl.com/pages/podcast'],
  ['India Energy Week','https://iocl.com/pages/iew'],
  ['iew','https://iocl.com/pages/iew'],
  ['indian oil motorists','https://iocl.com/pages/XP95'],
  ['xp95','https://iocl.com/pages/XP95'],
  ['ocatane gasoline','https://iocl.com/pages/XP95'],
  ['extra green','https://iocl.com/pages/XtraGreen'],
  ['xtra green','https://iocl.com/pages/XtraGreen'],
  ['compressed natural gas','https://iocl.com/pages/cng'],
  ['cng','https://iocl.com/pages/cng'],
  ['petrol gasoline','https://iocl.com/petrol-gasoline'],
  ['pg','https://iocl.com/petrol-gasoline'],
  ['high speed diesel','https://iocl.com/high-speed-diesel'],
  ['hsd','https://iocl.com/high-speed-diesel'],
  ['h s d','https://iocl.com/high-speed-diesel'],
  ['XP100','https://iocl.com/xp100'],
  ['premium petrol','https://iocl.com/xp100'],
  ['swagat retail outlets','https://swagat.iocxtrapower.com/'],
  ['swagat outlet map','https://swagat.iocxtrapower.com/search.php?view=map'],
  ['SERVO Lubes and Greases','https://iocl.com/pages/servo-lubes-and-greases-overview'],
  ['servo lubes and greases automotive greases','https://iocl.com/automotive-greases'],
  ['Automotive Lubricating Oils','https://iocl.com/automotive-lubricating-oils'],
  ['Automotive Speciality Oils','https://iocl.com/automotive-speciality-oils'],
  ['feedback and suggestion','https://cx.indianoil.in/EPICIOCL/faces/GrievanceMainPage.jspx'],
  ['frequently asked questions','https://iocl.com/pages/LubesGreasesFAQ'],
  ['AutoGas','https://iocl.com/autogas-overview'],
  ['Test Fuel Samples','https://iocl.com/test-fuel-samples'],
  ['tfs','https://iocl.com/test-fuel-samples'],
  ['fuel station locator','https://associates.indianoil.co.in/PumpLocator/'],
  ['fsl','https://associates.indianoil.co.in/PumpLocator/'],
  ['News Releases', 'https://iocl.com/news-releases']
  
  

  
  ];

// Generate the data array based on the keywordURLPairs
const data = keywordURLPairs.map(pair => {
  return {
    keyword: pair[0],
    url: pair[1]
  };
});
